"""Add ai enrichment table

Revision ID: 008e864838e8
Revises: cc54328b9133
Create Date: 2025-04-05 07:03:20.232905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008e864838e8'
down_revision: Union[str, None] = 'cc54328b9133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_enrichment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recording_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_enrichment_id'), 'ai_enrichment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_enrichment_id'), table_name='ai_enrichment')
    op.drop_table('ai_enrichment')
    # ### end Alembic commands ###
