"""Remove FK contstraint to recording on event table

Revision ID: 499ba96ce072
Revises: b02ff97b8280
Create Date: 2025-04-07 07:18:47.904808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499ba96ce072'
down_revision: Union[str, None] = 'b02ff97b8280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'recording_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('events_recording_id_fkey', 'events', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('events_recording_id_fkey', 'events', 'recording', ['recording_id'], ['id'], ondelete='CASCADE')
    op.alter_column('events', 'recording_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
