"""Fix event tracker table

Revision ID: b02ff97b8280
Revises: bf77f57660c1
Create Date: 2025-04-07 07:13:32.850871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b02ff97b8280'
down_revision: Union[str, None] = 'bf77f57660c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('stream_name', sa.String(), nullable=False))
    op.add_column('events', sa.Column('redis_id', sa.String(), nullable=False))
    op.add_column('events', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('payload', sa.JSON(), nullable=True))
    op.alter_column('events', 'recording_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'events', ['redis_id'])
    op.drop_column('events', 'event_type')
    op.drop_column('events', 'details')
    op.drop_column('events', 'event_timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='unique')
    op.alter_column('events', 'recording_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('events', 'payload')
    op.drop_column('events', 'timestamp')
    op.drop_column('events', 'redis_id')
    op.drop_column('events', 'stream_name')
    # ### end Alembic commands ###
