"""Remove FK constraint from recordings table on events

Revision ID: d1d4058adee9
Revises: 499ba96ce072
Create Date: 2025-04-07 07:32:53.683260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d4058adee9'
down_revision: Union[str, None] = '499ba96ce072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
