services:

  #############
  # Local only
  ############# 
  watcher:
    build:
      context: .
      dockerfile: src/services/watcher/Dockerfile
    volumes:
      - "./data/:/src/data/"
    environment:
      - DYNACONF_WATCHER__DATA_DIR=/src/data
    profiles:
      - local
      - test

  uploader:
    build:
      context: .
      dockerfile: src/services/uploader/Dockerfile
    volumes:
      - "${AUDIO_DIR}:/mnt/audio"
    profiles:
      - local
      - test

  redis:
    image: redis:7.4.2
    env_file:
      - .env
    container_name: redis_local
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - redis

  runpod_trigger:
    build:
      context: .
      dockerfile: src/services/runpod_trigger/Dockerfile
    env_file:
      - .env
    profiles:
      - prod
      - test

  web:
    build:
      context: .
      dockerfile: src/services/web/Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    profiles:
      - prod
      - test

  metadata_indexer:
    build:
      context: .
      dockerfile: src/services/metadata_indexer/Dockerfile
    env_file:
      - .env
    profiles:
      - prod
      - test

  ai_enrichment_engine:
    build:
      context: .
      dockerfile: src/services/ai_enrichment_engine/Dockerfile
    env_file:
      - .env
    profiles:
      - prod
      - test

  event_tracker:
    build:
      context: .
      dockerfile: src/services/event_tracker/Dockerfile
    env_file:
      - .env
    profiles:
      - prod
      - test


volumes:
  redis_data: