services:

  #############
  # Local only
  ############# 
  watcher:
    build:
      context: .
      dockerfile: src/services/watcher/Dockerfile
    volumes:
      - "./data/:/src/data/"
    environment:
      - JOURNAL_FILE=/app/data/journal.txt
    profiles:
      - local

  uploader:
    build:
      context: .
      dockerfile: src/services/uploader/Dockerfile
    volumes:
      - "${AUDIO_DIR}:/mnt/audio"
    profiles:
      - local

  redis:
    image: redis:7.4.2
    env_file:
      - .env
    container_name: redis_local
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - prod
      - test

  runpod_trigger:
    build:
      context: .
      dockerfile: src/services/runpod_trigger/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    profiles:
      - prod
      - test

volumes:
  redis_data: