services:

  redis:
    image: redis:7.4.2
    container_name: redis_local
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # watcher, runs locally always
  watcher:
    build:
      context: .
      dockerfile: src/services/watcher/Dockerfile
    volumes:
      - "./data/:/src/data/"
    environment:
      - JOURNAL_FILE=/app/data/journal.txt

  # uploader:
  #   build:
  #     context: .
  #     dockerfile: uploader/Dockerfile
  #   environment:
  #     - JOURNAL_FILE=/app/data/journal.txt

volumes:
  redis_data: