services:

  #############
  # Local only
  ############# 
  watcher:
    build:
      context: .
      dockerfile: src/services/watcher/Dockerfile
    volumes:
      - "./data/:/src/data/"
    environment:
      - DYNACONF_WATCHER__DATA_DIR=/src/data
    profiles:
      - local
      - test
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  uploader:
    build:
      context: .
      dockerfile: src/services/uploader/Dockerfile
    volumes:
      - "${AUDIO_DIR}:/mnt/audio"
    profiles:
      - local
      - test
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7.4.2
    env_file:
      - .env
    container_name: redis_local
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - redis
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  runpod_trigger:
    build:
      context: .
      dockerfile: src/services/runpod_trigger/Dockerfile
    env_file:
      - .env
    profiles:
      - prod
      - test
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build:
      context: .
      dockerfile: src/services/web/Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    profiles:
      - prod
      - test
      - web
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  metadata_indexer:
    build:
      context: .
      dockerfile: src/services/metadata_indexer/Dockerfile
    env_file:
      - .env
    profiles:
      - prod
      - test
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  ai_enrichment_engine:
    build:
      context: .
      dockerfile: src/services/ai_enrichment_engine/Dockerfile
    env_file:
      - .env
    profiles:
      - prod
      - test
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  event_tracker:
    build:
      context: .
      dockerfile: src/services/event_tracker/Dockerfile
    env_file:
      - .env
    profiles:
      - prod
      - test
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  notion_export:
    build:
      context: .
      dockerfile: src/services/notion_export/Dockerfile
    env_file:
      - .env
    profiles:
      - prod
      - test
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis_data:
