redis:
  host: capital-cricket-43383.upstash.io
  port: 6379
  streams:
    journal_steam_name: journal
    audio_upload_complete_local: audio_upload_complete_local
    audio_upload_complete_remote: audio_upload_complete_remote
    transcription_complete: transcription_complete

db: 
  provider: postgres
  host: db.miyxlnappsokgyfbqfem.supabase.co
  port: 5432
  user: postgres
  database: postgres

s3:
  url: https://s3.us-west-004.backblazeb2.com
  bucket-name: automeet-bucket
  application_key:
  application_key_id:

runpod:
  api_key:
  endpoint_id: txbdniwz0qsow7

watcher:
  data_dir: "~/AudioHijackLogs" 

uploader:
  consumer_group: uploader-group
  audio_dir: /mnt/audio
  run_mode: runpod

runpod_trigger:
  consumer_group: runpod_trigger
  
web:

whisper_worker:
  redis_enabled: true
  local_model_dir: "./model"  # Optional
  hf_token:

  whisper_model:
    language: "en"
    model_size: "large-v3-turbo"
    compute_type: "int8"
    device: "cpu"
    batch_size: 16

  speaker_diarization:
    use_diarization: true
