redis:
  host: redis_local
  port: 6379
  streams:
    journal_steam_name: journal

s3:
  url: https://s3.us-west-004.backblazeb2.com
  bucket-name: automeet-bucket

watcher:
  journal_file: data/journal.txt
  failed_file: data/failed.txt
  processed_file: data/processed.txt

uploader:
  consumer_group: uploader-group

web:
  paths:
    audio_input_dir: "/Users/erickshaffer/Music/Audio Hijack"
    output_dir: "./transcripts"

whisper_worker:
  local_model_dir: "./model"  # Optional

  whisper_model:
    language: "en"
    model_size: "large-v2"
    compute_type: "int8"
    device: "cpu"
    batch_size: 16

  speaker_diarization:
    use_diarization: true
