redis:
  host: redis_local
  port: 6379
  streams:
    journal_steam_name: journal

watcher:
  journal_file: data/journal.txt
  failed_file: data/failed.txt
  processed_file: data/processed.txt

uploader:
  consumer_group: uploader-group

web:
  paths:
    audio_input_dir: "/Users/erickshaffer/Music/Audio Hijack"
    output_dir: "./transcripts"
    local_model_dir: "./model"  # Optional

  whisper_model:
    language: "en"
    model_size: "large-v2"
    compute_type: "int8"
    device: "cpu"
    batch_size: 16

  speaker_diarization:
    use_diarization: true

