redis:
  host: redis_local
  port: 6379
  streams:
    journal_steam_name: journal
    audio_upload_complete_local: audio_upload_complete_local
    audio_upload_complete_remote: audio_upload_complete_remote

s3:
  url: https://s3.us-west-004.backblazeb2.com
  bucket-name: automeet-bucket
  application_key:
  application_key_id:

runpod:
  api_key:

watcher:
  journal_file: data/journal.txt
  failed_file: data/failed.txt
  processed_file: data/processed.txt

uploader:
  consumer_group: uploader-group
  audio_dir: /mnt/audio
  run_mode: runpod

runpod_trigger:
  consumer_group: runpod_trigger
  

web:
  paths:
    audio_input_dir: "/Users/erickshaffer/Music/Audio Hijack"
    output_dir: "./transcripts"

whisper_worker:
  local_model_dir: "./model"  # Optional
  hf_token:

  whisper_model:
    language: "en"
    model_size: "large-v3-turbo"
    compute_type: "int8"
    device: "cpu"
    batch_size: 16

  speaker_diarization:
    use_diarization: true
