FROM python:3.10-slim

WORKDIR /src

COPY src/services/runpod_trigger/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/services/runpod_trigger /src/services/runpod_trigger

COPY src/shared /src/shared
COPY src/config /src/config

ENV PYTHONPATH=/src
ENV DYNACONF_SETTINGS=/src/config/settings.yaml  

CMD ["python", "-u", "/src/services/runpod_trigger/handler.py", "--rp_serve_api", "--rp_api_host", "0.0.0.0"]