name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            echo "[*] Ensuring repo is cloned..."

            if [ ! -d /opt/automeet ]; then
              git clone https://github.com/eshaffer321/AutoMeet.git /opt/automeet
            else
              cd /opt/automeet
              git pull origin main
            fi

            cd /opt/automeet

            echo "[*] Creating secrets.env..."
            cat <<EOF > .env
            AUDIO_DIR=/opt/
            DYNACONF_s3__application_key=${{ secrets.DYNACONF_S3__APPLICATION_KEY }}
            DYNACONF_s3__application_key_id=${{ secrets.DYNACONF_S3__APPLICATION_KEY_ID }}
            DYNACONF_runpod__api_key=${{ secrets.DYNACONF_RUNPOD__API_KEY }}
            DYNACONF_redis__password=${{ secrets.DYNACONF_REDIS__PASSWORD }}
            DYNACONF_db__password=${{ secrets.DYNACONF_DB__PASSWORD }}
            DYNACONF_db__user=${{ secrets.DYNACONF_DB__USER }}
            DYNACONF_db_host=${{ secrets.DYNACONF_DB__HOST }}
            EOF

            echo "[*] Deploying via Docker Compose..."
            docker-compose pull
            docker-compose --profile prod up -d --build
